# Generated by Django 3.1.3 on 2020-11-29 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('months', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('perdiem', models.IntegerField(default=150000)),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.FloatField(default=0.4)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcapp.bundle')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcapp.resource')),
            ],
        ),
        migrations.AddField(
            model_name='bundle',
            name='members',
            field=models.ManyToManyField(through='calcapp.Membership', to='calcapp.Resource'),
        ),
    ]
