# Generated by Django 3.1.3 on 2020-11-25 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=50)),
                ('months', models.IntegerField(default=0)),
                ('jr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcapp.resource')),
            ],
        ),
    ]
