# Generated by Django 3.1.3 on 2020-11-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(verbose_name=True)),
                ('name', models.CharField(max_length=200)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcapp.bundle')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
