# Generated by Django 3.1.3 on 2020-11-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0002_auto_20201125_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ['bundle_name']},
        ),
        migrations.RenameField(
            model_name='bundle',
            old_name='nameid',
            new_name='bundle_name',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='nameid',
            new_name='resource_name',
        ),
    ]
